[package]
name = "poll-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"]}
config = "0.13.3"
serde = { version = "1.0.152", features = ["derive"] }
serde-aux = "4.1.2"
