application:
  port: 8000
  allowed_origin: "http://localhost:5173"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "poll"
  timeout_milliseconds: 2000
